version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - application
  lgm-backend:
    image: lgm-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    networks:
      - application
  lgm-frontend:
    image: lgm-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - lgm-backend
    networks:
      - application

networks:
  application:
    name: application
    driver: bridge