package com.lgm.demo.service.impl;

import com.lgm.demo.model.*;
import com.lgm.demo.model.payload.request.LeagueRequest;
import com.lgm.demo.model.payload.response.CompetitorStandingsLeagueResponse;
import com.lgm.demo.model.payload.response.MatchResponse;
import com.lgm.demo.repository.CompetitionRepository;
import com.lgm.demo.repository.MatchRepository;
import com.lgm.demo.repository.UserRepository;
import com.lgm.demo.service.*;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@AllArgsConstructor
@Service
public class LeagueServiceImpl implements LeagueService {
    private CompetitorService competitorService;
    private ScheduleService scheduleService;
    private CompetitionRepository competitionRepository;
    private StandingsService standingsService;
    private AuthService authService;
    private UserRepository userRepository;
    private MatchRepository matchRepository;

    @Override
    public League createLeague(LeagueRequest req) {
        // maybe make builder for League
        League league = new League(
                null,
                null,
                null,
                req.getNumberOfCompetitors(),
                req.getCompetitionStart(),
                req.getDaysBetweenMatches(),
                null,
                req.getLeagueName(),
                req.getPointsWin(),
                req.getPointsDraw(),
                req.getPointsLose(),
                null,
                req.getTimesEachPlaysWithEach()
        );
        league.setCompetitors(competitorService.createEmptyCompetitors(league));
        competitionRepository.save(league);
        league.setSchedule(scheduleService.createRoundRobinSchedule(league));
        competitionRepository.save(league); // I'm saving league because in next line I will need ids that will be generated by saving to database
        league.setStandings(standingsService.createLeagueStandings(league));
        competitionRepository.save(league);

        // set user who created league as its admin

        User user = authService.getLoggedInUser();
        List<Long> adminOfCompetitions = user.getAdminOfCompetitions();
        adminOfCompetitions.add(league.getId());
        user.setAdminOfCompetitions(adminOfCompetitions);
        userRepository.save(user);

        return league;
    }

    @Override
    public List<CompetitorStandingsLeagueResponse> getStandings(Long leagueId) {
        List<CompetitorStandingsLeagueResponse> leagueStandingsResponses = CompetitorStandingsLeagueResponse
                .entityToDtoList(standingsService.getLeagueStandings(leagueId));
        for(CompetitorStandingsLeagueResponse leagueStandingsResponse : leagueStandingsResponses) {
            leagueStandingsResponse.setCompetitorName(
                    competitorService.getName(leagueStandingsResponse.getCompetitorId())
            );
        }
        return leagueStandingsResponses;
    }

    @Override
    public List<MatchResponse> getSchedule(Long competitionId, Integer round) {
        List<Match> matches = matchRepository.getMatchesByCompetitionIdAndRound(competitionId, round);
        List<MatchResponse> ret = new ArrayList<>();
        for(Match match : matches){
            MatchResponse matchResponse = MatchResponse.convertToMatchResponse(match);
            matchResponse.setFirstCompetitorName(competitorService.getName(match.getFirstCompetitorId()));
            matchResponse.setSecondCompetitorName(competitorService.getName(match.getSecondCompetitorId()));
            ret.add(matchResponse);
        }
        return ret;
    }
}
