
#Spring DataSource
spring.datasource.driverClassName=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/lgm
spring.datasource.username=postgres
spring.datasource.password=postgres

#JPA-Hibernate
spring.jpa.show-sql = true

#kreira tabele na osnovu anotacija @Entity i kada aplikacija zavrsi sa radom dropuje ih
spring.jpa.hibernate.ddl-auto = create-drop

#https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#optimizacija za postgres upite
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL95Dialect

# App Properties
lgm.app.jwtSecret = secrett
lgm.app.jwtExpirationMs = 86400000